CREATE TABLE catalogo_itens (
    id SERIAL PRIMARY KEY,
    identificador VARCHAR(100) UNIQUE,
    titulo VARCHAR(500) NOT NULL,
    data_captacao DATE,
    area_fazenda_id INT,
    ponto_id INT,
    tipo_projeto_id INT,
    nucleo_pecuaria_id INT,
    nucleo_agro_id INT,
    operacao_id INT,
    marca_id INT,
    tema_principal_id INT,
    tema_secundario_id INT,
    funcao_historica_id INT,
    evento_id INT,
    capitulo_id INT,
    status_id INT,
    frase_memoria TEXT,
    link_arquivo TEXT,
    link_pasta TEXT,
    link_aprovacao TEXT,
    link_tarefa TEXT,
    responsavel VARCHAR(255),
    observacoes TEXT,
    arquivo_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);